// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VipshopWeb.Infrastructure;

#nullable disable

namespace VipshopWeb.Infrastructure.Migrations
{
    [DbContext(typeof(VipshopDbContext))]
    [Migration("20260609001014_AtualizarEstruturaItensEProdutos")]
    partial class AtualizarEstruturaItensEProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VipshopWeb.Core.Entities.Cliente", b =>
                {
                    b.Property<Guid>("FavorecidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("favorecido_id");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("numeric")
                        .HasColumnName("limite_credito");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.HasKey("FavorecidoId");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Favorecido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("NomeFantasiaApelido")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_fantasia_apelido");

                    b.Property<string>("NomeRazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_razao_social");

                    b.Property<int>("TipoFavorecidoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_favorecido_id");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tipo_pessoa");

                    b.HasKey("Id");

                    b.HasIndex("TipoFavorecidoId");

                    b.ToTable("favorecidos");
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("FavorecidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("favorecido_id");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<int>("PrazoEntregaEstimadoDias")
                        .HasColumnType("integer")
                        .HasColumnName("prazo_entrega_estimado_dias");

                    b.HasKey("FavorecidoId");

                    b.ToTable("fornecedores");
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("FavorecidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("favorecido_id");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Ctps")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ctps");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_admissao");

                    b.Property<decimal>("Salario")
                        .HasColumnType("numeric")
                        .HasColumnName("salario");

                    b.HasKey("FavorecidoId");

                    b.ToTable("funcionarios");
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Custo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Itens", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.TipoFavorecido", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("tipos_favorecidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Cliente"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Fornecedor"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Funcionário"
                        });
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.ToTable("usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Ativo = true,
                            Login = "admin",
                            Nome = "Administrador Vipshop",
                            SenhaHash = "123"
                        });
                });

            modelBuilder.Entity("VipshopWeb.Core.EntitiesCatalog.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj_cpf");

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_contratacao");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razao_social");

                    b.HasKey("Id");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Produto", b =>
                {
                    b.HasBaseType("VipshopWeb.Core.Entities.Item");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("QuantidadeEstoque")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade_estoque");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnidadeVenda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Servico", b =>
                {
                    b.HasBaseType("VipshopWeb.Core.Entities.Item");

                    b.Property<decimal>("QuantidadeMaoObra")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TempoOcupacao")
                        .HasColumnType("integer");

                    b.ToTable("Servicos", (string)null);
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Cliente", b =>
                {
                    b.HasOne("VipshopWeb.Core.Entities.Favorecido", "Favorecido")
                        .WithOne("Cliente")
                        .HasForeignKey("VipshopWeb.Core.Entities.Cliente", "FavorecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorecido");
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Favorecido", b =>
                {
                    b.HasOne("VipshopWeb.Core.Entities.TipoFavorecido", "TipoFavorecido")
                        .WithMany()
                        .HasForeignKey("TipoFavorecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoFavorecido");
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Fornecedor", b =>
                {
                    b.HasOne("VipshopWeb.Core.Entities.Favorecido", "Favorecido")
                        .WithOne("Fornecedor")
                        .HasForeignKey("VipshopWeb.Core.Entities.Fornecedor", "FavorecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorecido");
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Funcionario", b =>
                {
                    b.HasOne("VipshopWeb.Core.Entities.Favorecido", "Favorecido")
                        .WithOne("Funcionario")
                        .HasForeignKey("VipshopWeb.Core.Entities.Funcionario", "FavorecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorecido");
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Produto", b =>
                {
                    b.HasOne("VipshopWeb.Core.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("VipshopWeb.Core.Entities.Produto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Servico", b =>
                {
                    b.HasOne("VipshopWeb.Core.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("VipshopWeb.Core.Entities.Servico", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VipshopWeb.Core.Entities.Favorecido", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Fornecedor");

                    b.Navigation("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
